services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - db_data:/app/data
      - socket:/tmp
      - static:/app/rpi/server/static
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/dht.sqlite3
    command: uvicorn rpi.server:app --uds /tmp/uvicorn.sock

  dht-polling:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - db_data:/app/data
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/dht.sqlite3
      - MOCK_SENSORS=1
    command: python -m rpi.dht

  pico-reader:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - db_data:/app/data
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/dht.sqlite3
      - MOCK_SENSORS=1
    command: python -m rpi.pico

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/rpi-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/html/static:ro
      - socket:/tmp
    depends_on:
      - app

volumes:
  db_data:
    name: rpi-gardener-dev-db
  socket:
    name: rpi-gardener-dev-socket
  static:
    name: rpi-gardener-dev-static
